site_name: LightKube
theme:
  name: material
  hljs_style: monokai
  palette:
    primary: deep purple

repo_name: gtsystem/lightkube
repo_url: https://github.com/gtsystem/lightkube
edit_uri: ""

nav:
  - QuickStart: index.md
  - Configuration: configuration.md
  - Client Interface: client.md
  - Resources & Models: resources-and-models.md
  - Async Usage: async-usage.md
  - Advanced:
      - Exceptions: exceptions.md
      - Selectors: selectors.md
      - Generic Resources: generic-resources.md
      - Load/Dump Objects: codecs.md

extra_css:
  - css/custom.css

markdown_extensions:
  - admonition
  - mkautodoc
  - pymdownx.highlight
  - pymdownx.superfences
  - markdown_include.include:
      base_path: .
